state2majorcity = {"MA": "Boston"}

state2redlining = {
    "PA": ["../data/input/redlining/PAPhiladelphia1937.geojson"],
    "MD": ["../data/input/redlining/MDBaltimore1937.geojson"],
    "MA": ["../data/input/redlining/MABoston1938.geojson"],
    "RI": ["../data/input/redlining/RIProvidence19XX.geojson"],
    "NJ": ["../data/input/redlining/NJEssexCo1939.geojson"],
    "NY": [
        "../data/input/redlining/NYBronx1938.geojson",
        "../data/input/redlining/NYBrooklyn1938.geojson",
        "../data/input/redlining/NYManhattan1937.geojson",
        "../data/input/redlining/NYQueens1938.geojson",
        "../data/input/redlining/NYStatenIsland1940.geojson",
    ],
}

state2address = {
    "CT": ["../data/open_address/original/city_of_hartford-addresses-city.geojson"],
    "DE": ["../data/open_address/original/city_of_dover-addresses-city.geojson"],
    "DC": ["../data/open_address/original/dc_statewide-addresses-city.geojson"],
    "ME": ["../data/open_address/original/me_statewide-addresses-state.geojson"],
    "MD": ["../data/open_address/original/city_of_baltimore-addresses-city.geojson"],
    "MA": ["../data/open_address/original/city_of_boston-addresses-city.geojson"],
    "NH": ["../data/open_address/original/city_of_nashua-addresses-city.geojson"],
    "NJ": ["../data/open_address/original/nj_statewide-addresses-state.geojson"],
    "NY": ["../data/open_address/original/city_of_new_york-addresses-city.geojson"],
    "PA": ["../data/open_address/original/philadelphia-addresses-county.geojson"],
    "RI": ["../data/open_address/original/providence-addresses-city.geojson"],
    "VT": ["../data/open_address/original/city_of_burlington-addresses-city.geojson"],
    "VA": ["../data/open_address/original/city_of_norfolk-addresses-city.geojson"],
    "WV": ["../data/open_address/original/wv_statewide-addresses-state.geojson"],
}

city2ap = {
    "Albuquerque": "Albuquerque, N.M.",
    "Atlanta": "Atlanta, Ga.",
    "Baltimore": "Baltimore, Md.",
    "Billings": "Billings, Mont.",
    "Boise": "Boise, Idaho",
    "Boston": "Boston, Mass.",
    "Charleston": "Charleston, S.C.",
    "Charlotte": "Charlotte, N.C.",
    "Cheyenne": "Cheyenne, Wyo.",
    "Chicago": "Chicago, Ill.",
    "Columbus": "Columbus, Ohio",
    "Denver": "Denver, Colo.",
    "Des Moines": "Des Moines, Iowa",
    "Detroit": "Detroit, Mich.",
    "Fargo": "Fargo, N.D.",
    "Houston": "Houston, Texas",
    "Huntsville": "Huntsville, Ala.",
    "Indianapolis": "Indianapolis, Ind.",
    "Jackson": "Jackson, Miss.",
    "Jacksonville": "Jacksonville, Fla.",
    "Kansas City": "Kansas City, Mo.",
    "Las Vegas": "Las Vegas, Nev.",
    "Little Rock": "Little Rock, Ark.",
    "Los Angeles": "Los Angeles, Calif.",
    "Louisville": "Louisville, Ky.",
    "Milwaukee": "Milwaukee, Wis.",
    "Minneapolis": "Minneapolis, Minn.",
    "Nashville": "Nashville, Tenn.",
    "New Orleans": "New Orleans, La.",
    "New York City": "New York, N.Y.",
    "Newark": "Newark, N.J.",
    "Oklahoma City": "Oklahoma City, Okla.",
    "Omaha": "Omaha, Neb.",
    "Philadelphia": "Philadelphia, Pa.",
    "Phoenix": "Phoenix, Ariz.",
    "Portland": "Portland, Ore.",
    "Providence": "Providence, R.I.",
    "Salt Lake City": "Salt Lake City, Utah",
    "Seattle": "Seattle, Wash",
    "Sioux Falls": "Sioux Falls, S.D.",
    "Virginia Beach": "Virginia Beach, Va.",
    "Washington": "Washington",
    "Wichita": "Wichita, Kan.",
}
